[package]
name = "ktail"
version = "0.1.0"
authors = ["nico.just <nico.just@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.10.1"
gdk = "0.13.1"
encoding = "0.2.33"
sourceview = {version = "0.9.0", features = ["v3_18"]}
serde = {version = "1.0.115", features = ["derive"]}
serde_json = "1.0.57"
log4rs = "0.13.0"
log = "0.4.11"

regex = "1.3.9"
uuid = {version = "0.8.1", features = ["v4"]}

[dependencies.gtk]
version = "0.9.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]


[profile.release]
opt-level = 'z' # Optimize for size.
lto = true
codegen-units = 1
panic = 'abort'