name: MacOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Install cargo-bundle
      run: cp ./assets/MacOS/cargo-bundle ~/.cargo/bin
    - name: Install gtk prerequsites
      run: brew install gtk+3 gtksourceview3
    - uses: actions/checkout@v2
    - name: Build
      run: cargo-bundle bundle --release --format osx
    - name: Generate Bundle
      run: ./generate-macos-bundle.sh
    - uses: actions/upload-artifact@v2
      with:
        name: kTail
        path: target/release/bundle/osx/ktail.app