name: Publish release

on:
  workflow_run:
    workflows: ["Linux Build"]
    types:
      - completed
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success
        name: kTail