name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install Windows GNU Toolchain
      run: rustup default stable-x86_64-pc-windows-gnu
    - name: Refresh env
      run: refreshenv
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit
        install: >-
          base-devel
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-gtksourceview3
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: kTail
        path: target/release/ktail.exe