name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install msys2
      run: choco install -y msys2 --params "/NoUpdate /InstallDir:C:\msys2"
    - name: Install gtk prerequsites
      run: mingw64.exe pacman --noconfirm -S mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-gtk3 mingw-w64-x86_64-gtksourceview3
      working-directory: C:/msys2/
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: kTail
        path: target/release/ktail.exe