name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Windows GNU Toolchain
      run: rustup default stable-x86_64-pc-windows-gnu
    - uses: msys2/setup-msys2@v2
      with:
        update: false
        path-type: inherit
        install: >-
          mingw-w64-x86_64-toolchain
          base-devel
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-gtksourceview3
    - name: Test
      run: msys2 -c 'where pacman'
    - name: List files
      run: Get-ChildItem -Recurse "D:\a\_temp\msys\msys64\mingw64"
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: msys2 -c 'cargo build --release --verbose'
    - uses: actions/upload-artifact@v2
      with:
        name: kTail
        path: target/release/ktail.exe
    - name: Generate Bundle
      run: .\generate-bundle.ps1
      shell: powershell
    - uses: actions/upload-artifact@v2
      with:
        name: bundle
        path: ktail