name: Windows Build

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: false
          path-type: inherit
          install: >-
            base-devel
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gtksourceview5

      - name: Install Windows GNU Toolchain
        run: rustup default stable-x86_64-pc-windows-gnu
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo build
        run: msys2 -c 'cargo build --release'
      - name: Download theme
        run: msys2 -c 'wget https://github.com/vinceliuice/Orchis-theme/raw/master/release/Orchis.tar.xz && tar --xz -xvf Orchis.tar.xz Orchis-Light-Compact/gtk-4.0 Orchis-Light-Compact/COPYING Orchis-Light-Compact/index.theme'
      - name: Create Bundle
        run: .\createWindowsBundle.ps1
        shell: powershell
      - uses: actions/upload-artifact@v2
        with:
          name: KTail-x64-win.zip
          path: KTail-x64-win.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: KTail-x64-win.zip